sudo: required

services:
  - docker

before_script:
  - .travis/export_environment.sh

env:
  global:
    - BUILD_DATE=$(date +"%Y-%m-%d")

stages:
  - build

jobs:
  include:
    - stage: build
      script:
        - .travis/export_environment.sh
        - make build
        - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
        - make release
        - docker logout

#install:
#  - docker build --tag bodsch/docker-mysql .
#  - docker run --detach --name mysql bodsch/docker-mysql
#
#script:
#  - docker ps | grep -q mysql

