sudo: required

services:
  - docker

env:
  global:
    - BUILD_DATE=$(date +%Y-%m-%d)
    - BUILD_VERSION=$(date +%y%m)
    - VERSION=$(.travis/export_environment.sh)

jobs:
  include:
    - stage: build
      script:
        - make

    - stage: test
      script:
        - make
        - make compose-file
        - docker-compose build
        - docker-compose up -d
        - tests/test.sh
        - docker-compose kill
        - docker-compose down

    - stage: push latest docker image
      script:
        - make
        - docker tag ${DOCKER_USERNAME}/docker-mysql:${VERSION} ${DOCKER_USERNAME}/docker-mysql:latest
        - docker login --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}"
        - docker push ${DOCKER_USERNAME}/docker-mysql:latest
        - docker logout

    - stage: push version docker image
        - make
        - docker login --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}"
        - docker push ${DOCKER_USERNAME}/docker-mysql:${VERSION}
        - docker logout
