sudo: required

services:
  - docker

before_script:
  - .travis/export_environment.sh

env:
  global:
    - BUILD_DATE=$(date +"%Y-%m-%d")
  matrix:
    - MARIADB_VERSION=$(cat ~/.deployment-env)

jobs:
  include:
    - stage: build, test and push docker image
      script:
        - make build
        - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
        - docker push ${DOCKER_USERNAME}/docker-mysql:${MARIADB_VERSION}
        - docker logout

#install:
#  - docker build --tag bodsch/docker-mysql .
#  - docker run --detach --name mysql bodsch/docker-mysql
#
#script:
#  - docker ps | grep -q mysql

