sudo: required

services:
  - docker

#install:
#  - docker build --tag bodsch/docker-mysql .
#  - docker run --detach --name mysql bodsch/docker-mysql
env:
  global:
    - ETCD_VERSION=${ETCD_VERSION:-3.3.7}
    - BUILD_DATE=$(date +%Y-%m-%d)
    - BUILD_VERSION=$(date +%y%m)
    - BUILD_TYPE=stable

jobs:
  include:
    - stage: build
      script:
        - make build

    - stage: test plain
      script:
        - docker-compose --file docker-compose_example.yml up --build -d
        - docker-compose --file docker-compose_example.yml kill
        - docker-compose --file docker-compose_example.yml down

    - stage: test with consul
      script:
        - docker-compose --file docker-compose_example_consul.yml up --build -d
        - docker-compose --file docker-compose_example_consul.yml kill
        - docker-compose --file docker-compose_example_consul.yml down

    - stage: test with etcd
      script:
        - docker-compose --file docker-compose_example_etcd.yml up --build -d
        - docker-compose --file docker-compose_example_etcd.yml kill
        - docker-compose --file docker-compose_example_etcd.yml down

    - stage: build and release
      script:
        - make build
        - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
        - make release
        - docker logout
