---
version: '3.3'

volumes:
  etcd:
    driver: local

services:

  etcd:
    restart: always
    image: bodsch/docker-etcd:3.3.7
    container_name: etcd
    hostname: etcd
    ports:
      - 2379:2379
      - 2380:2380
    command: "--data-dir /data --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://0.0.0.0:2380"
    volumes:
      - etcd:/data

  database:
    #image: bodsch/docker-mysql:10.1.28-r1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_DATE=${BUILD_DATE}
    container_name: database
    hostname: database
    environment:
      - DEBUG=true
#      - MYSQL_SYSTEM_USER=root
#      - MYSQL_ROOT_PASS=vYUQ14SGVrJRi69PsujC
      - CONFIG_BACKEND=etcd
      - CONFIG_BACKEND_SERVER=etcd
    links:
      - etcd
