---
version: '3.3'

services:

  database:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_DATE=${BUILD_DATE}
        - BUILD_VERSION=${BUILD_VERSION}
    restart: always
    container_name: database
    hostname: database
    ports:
      - 33060:3306
    environment:
      - MYSQL_SYSTEM_USER=${MYSQL_SYSTEM_USER}
      - MYSQL_ROOT_PASS=${MYSQL_ROOT_PASS}
