#!/bin/sh

shutdown() {

  echo "`date +"%d.%m.%Y %T.%3N"` - Shutting down mysql"

  kill -15 $(cat /app/mysql/$(hostname).pid)
#  /etc/init.d/mysql stop
}

echo "`date +"%d.%m.%Y %T.%3N"` - Starting mysql"

# /etc/init.d/mysql start

exec /usr/bin/mysqld --user=root --console &

# Allow any signal which would kill a process to stop server
trap shutdown HUP INT QUIT ABRT KILL ALRM TERM TSTP

while pgrep -u mysql mysql > /dev/null; do sleep 5; done
